### PR TITLE
Fix issues with failed JSON parsing in JS API responses

### LINKED ISSUE #390: Special characters seem to affect getScenes and getTransitions
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

29.0.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/BdNarNPBbQaO1YOz

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Whenever using `window.obsstudio.getScenes` or `window.obsstudio.getTransitions` in OBS, I expect to receive the list of scenes or transitions available.

### Current Behavior

If one uses `window.obsstudio.getScenes` or `window.obsstudio.getTransitions` whenever a scene with special characters such as ', ", \ the callback passed to the functions is not invoked.

### Steps to Reproduce

1. Start OBS with remote debugging `$ ./obs64.exe --remote-debugging-port=9222`
2. In any scene, create a browser source with Page permissions 'Read access to user information'
3. Check for the list of scenes from the inspector (`http://localhost:9222/`) by running `window.obsstudio.getScenes((a) => {console.log(a)})` for the previously created browser source. The callback will be invoked `> ['OverlayTest', 'Webcam', 'Desktop', 'Demo', 'Other']`
4. Create a scene with one of these characters: ' , ", \
5. Perform step 3 again, this time the callback will not be invoked.

The same happens for transitions `getTransitions`

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by WizardCM**
### Description

Using a [forum post](https://magpcss.org/ceforum/viewtopic.php?f=10&t=14807#p33456) as reference, overhauled JSON handling internally to use CefValue rather than the V8 context.

Note: It seems the V8 context is still required in this code block. I am unsure exactly why (it crashes otherwise).

### Motivation and Context

When users call API functions, they expect a response. Especially a valid one. Fixes #390.

### How Has This Been Tested?

`obsstudio.getScenes` and `obsstudio.getCurrentScene` with scene names that contain characters such as `"` and `\`.

Also re-tested all other get functions to make sure nothing else was broken.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: browser-client.cpp [hunk 1]
```diff
@@ -206,13 +206,13 @@ bool BrowserClient::OnProcessMessageReceived(
...
 			obs_frontend_get_scenes(&list);
-			std::vector<const char *> scenes_vector;
+			std::vector<Json> scenes_vector;
 			for (size_t i = 0; i < list.sources.num; i++) {
 				obs_source_t *source = list.sources.array[i];
 				scenes_vector.push_back(
 					obs_source_get_name(source));
 			}
-			json = scenes_vector;
+			json = Json::array(scenes_vector);
```
Comment (tytan652) [inline browser-client.cpp:215]: nlohmann is smart enough to convert a vector of JSONs to a JSON array of objects. And `Json::array` is json11 only.
```suggestion
			json = scenes_vector;
```

File: browser-client.cpp [hunk 2]
```diff
@@ -234,13 +234,13 @@ bool BrowserClient::OnProcessMessageReceived(
...
 			obs_frontend_get_transitions(&list);
-			std::vector<const char *> transitions_vector;
+			std::vector<Json> transitions_vector;
 			for (size_t i = 0; i < list.sources.num; i++) {
 				obs_source_t *source = list.sources.array[i];
 				transitions_vector.push_back(
 					obs_source_get_name(source));
 			}
-			json = transitions_vector;
+			json = Json::array(transitions_vector);
```
Comment (tytan652) [inline browser-client.cpp:243]: nlohmann is smart enough to convert a vector of JSONs to a JSON array of objects. And `Json::array` is json11 only.
```suggestion
			json = transitions_vector;
```

**Review by tytan652 — COMMENTED** [review]
You might need to check if conversion are done correctly. But it should be good once the added json11 stuff is removed.

File: browser-client.cpp (hunk 1 above)
Comment (WizardCM) [reply browser-client.cpp]: Confirmed. Scrapped the change on my side.

File: browser-client.cpp (hunk 2 above)
Comment (WizardCM) [reply browser-client.cpp]: Confirmed. Scrapped the change on my side.

**Comment by WizardCM** [comment]
Rebased on master (after fixing Nlohmann JSON compilation on Windows & macOS), removed unnecessary changes based on @tytan652's feedback, and retested with Nlohmann JSON specifically. It has the same output difference as json11 so this PR is still necessary to fix the linked issue.

Ready to be reviewed.
